CLOSE(101)
CLOSE(102)

DONE

// Turnouts
#define PULSE 50

#define ROKUHANTURNOUT(t, p1, p2, desc, ali) \
PIN_TURNOUT(t, 0, desc) \
ALIAS(ali, t) \
DONE \
ONCLOSE(t) \
SET(p1) \
SET(p2)DELAY(PULSE)RESET(p2) \
DONE \
ONTHROW(t) \
RESET(p1) \
SET(p2)DELAY(PULSE)RESET(p2) \
DONE \

ROKUHANTURNOUT(101, 50, 51, "Turnout 1", TRN_1)
ROKUHANTURNOUT(102, 2, 4, "Turnout 2", TRN_2)

// EX-Turntable routes
#define EX_TURNTABLE(route_id, reserve_id, vpin, steps, activity, desc) \
  ROUTE(route_id, desc) \
    RESERVE(reserve_id) \
    MOVETT(vpin, steps, activity) \
    WAITFOR(vpin) \
    FREE(reserve_id) \
    DONE

// Turntable
EX_TURNTABLE(TTROUTE1, TURNTABLE, 600, 500, Turn, "Position 1")
EX_TURNTABLE(TTROUTE2, TURNTABLE, 600, 600, Turn, "Position 2")
EX_TURNTABLE(TTROUTE3, TURNTABLE, 600, 700, Turn, "Position 3")
EX_TURNTABLE(TTROUTE4, TURNTABLE, 600, 800, Turn, "Position 4")
EX_TURNTABLE(TTROUTE5, TURNTABLE, 600, 900, Turn, "Position 5")
EX_TURNTABLE(TTROUTE6, TURNTABLE, 600, 1000, Turn, "Position 6")
EX_TURNTABLE(TTROUTE7, TURNTABLE, 600, 0, Home, "Home Turntable")
EX_TURNTABLE(TTROUTE8, TURNTABLE, 600, 0, Calibrate, "Calibrate Turntable")

// Traverser
EX_TURNTABLE(TRROUTE1, TRAVERSER, 601, 500, Turn, "Position 1")
EX_TURNTABLE(TRROUTE2, TRAVERSER, 601, 600, Turn, "Position 2")
EX_TURNTABLE(TRROUTE3, TRAVERSER, 601, 700, Turn, "Position 3")
EX_TURNTABLE(TRROUTE4, TRAVERSER, 601, 800, Turn, "Position 4")
EX_TURNTABLE(TRROUTE5, TRAVERSER, 601, 900, Turn, "Position 5")
EX_TURNTABLE(TRROUTE6, TRAVERSER, 601, 1000, Turn, "Position 6")
EX_TURNTABLE(TRROUTE7, TRAVERSER, 601, 0, Home, "Home Traverser")
EX_TURNTABLE(TRROUTE8, TRAVERSER, 601, 0, Calibrate, "Calibrate Traverser")

// Rotary encoder event handler
ONCHANGE(700)
  IFRE(700, 5)
    START(TTROUTE1)
  ENDIF
  DONE

// Loco roster entries
ROSTER(2004, "QR 2004", "Lights")
ROSTER(2006, "QR 2006", "Lights")
ROSTER(2010, "QR 2010", "Lights")

// Aliases
ALIAS(TURNTABLE, 255)
ALIAS(TRAVERSER, 254)
ALIAS(TTROUTE1)
ALIAS(TTROUTE2)
ALIAS(TTROUTE3)
ALIAS(TTROUTE4)
ALIAS(TTROUTE5)
ALIAS(TTROUTE6)
ALIAS(TTROUTE7)
ALIAS(TTROUTE8)
ALIAS(TRROUTE1)
ALIAS(TRROUTE2)
ALIAS(TRROUTE3)
ALIAS(TRROUTE4)
ALIAS(TRROUTE5)
ALIAS(TRROUTE6)
ALIAS(TRROUTE7)
ALIAS(TRROUTE8)