//ROSTER(0,"Default","Lights/Bell/Whistle/F3/F4/F5/F6/F7/F8")
ROSTER(3718, "Class 37 Loram Livery", "Lights/WarmEngineStart/Brake/*Single-Horn/*Double-Horn/Light Engine Mode/Coasting/Speed Lock/Sound Fade OutIn/Flange Squeal//*Buffer Up/*Coupling/STATIONARY-Guard's Whistle MOVING-Detonators/Wagon Snatching & Buffering/High Intensity Light-On/Red Tail Lights On Both Ends Non di/Marker Lights On Both Ends Non di/Cab Light On-No.1 End Fan/Cab Light On-No.2 End non fan/No.1 End Dir Lights Off/No.2 End Dir Lights Off/Compressor/Windscreen Wipers/Engine Room")
ROSTER(322,"A-T322-2","*Horn///Drive HOLD/Brake 2/Loco Brake 1/Loco Brake 3/HeadLightT322///Man Notch/Coast-Notch DN/Run 8-Notch UP///Fade/Uncouple/Compressor//Volume///TW//LIL////////")
ROSTER(323,"A-T323-S","HeadLightT323/////Loco Brake 1/Brake 2////Man Notching/*Coast-Notch DN/*Run8-Notch UP///Fade/Uncouple/Drive HOLD//Volume//Compressor////*Horn///////")
ROSTER(175,"A-Y175Sound","/Horn//Drive HOLD/Brake 2/Loco Brake 1//HeadLightY175/Engine Start-Stop/////Short Horn//Fade//Compressor/Reverser-Notching/Volume/////////////")

ROSTER(1012,"PA# 1012 2-6-6-2T","Lights/////////////////////////////")
ROSTER(1111,"PA# 1111 Gandy Dancer","Light/////////////////////////////")
ROSTER(1632,"PA# 1632 2-10-0","/////////////////////////////")
//duplicate address not supported, skipping: ROSTER(1632,"PA# 1632 New RMCQHO","/////////////////////////////")
ROSTER(2511,"PA# 2511 snd 2-8-0","Lights/Bell/*Whistle/*Coupler/Air feat. disabled/*Dyn. Brakes Fans -Water Pump/*Notch UP-Blowdown/*Xing Gate Airhorn -Notch DOWN/Mute/*Brake squeal/*Xing Gate Airhorn -Wheel Slip/*Handbrake -Greaser/*Safety Blow off/////////////////")
ROSTER(2528,"PA# 2528 snd 2-8-0","Lights/Bell/*Whistle/*Coupler/Air feat. disabled/*Dyn. Brakes Fans-Water Pump/*Notch UP-Blowdown/*Xing Gate Airhorn-Notch DOWN/Mute/*Brake squeal/*Xing Gate Airhorn-Wheel Slip/*Handbrake-Greaser/*Safety Blow off/////////////////")
ROSTER(3528,"PA# 3528 2-8-0","Light/////////////////////////////")
ROSTER(3932,"PA# 3932 2-6-6-2","Lights/Bell/*Whistle/*Long Air Release/*Coupling 1/*Break Squeal-Release/*All Aboard/*Firebox Open-Close/*Water Injector/*Metel Crank Sound on-oof/*Water Filling/*Blower hiss/Mute On-Off/*Vol -/*Vol +/*Flange noise/*Shoveling/*Coal auger/*Bell Type (7)/*Whis. Type (17)/*Air hose firing/*Flange Noise/*Ass.Loco Sound/*Flange noise/*Chuff Type/*Long air Release/*Sand Droping/*Assoc Loco Sound//")
ROSTER(7407,"PA# 7407 BX snd","Lights/Bell/*Whistle/*Long Air Release/*Coupling 1/*Brake Squeal/Chuff On-Off/*Firebox Open-Close/*Water Injector/*Metel Crank Sound on-oof/*Water Filling/*Blower hiss/Mute/*Vol -/*Vol +/*Flange noise/*Shoveling/*Coal auger/*B.ell Type (7)/*W.histle Type (17)/*Air hose firing/*Flange Noise/*Assoc Loco Sound/*Flange noise/*C.huff Type/*Long air Release/*Sand Droping/*Assoc Loco Sound/*Assoc Loco Sound/")
ROSTER(112,"PA# _112 Heisler","LIghts/////////////////////////////")
ROSTER(1117,"PA# _117 Heisler","Lights/////////////////////////////")
ROSTER(1127,"PA# _127 0-8-0","Light/Bell/*Whistle/*Coupler/Blower Hiss/Dyn Brake/*Dplr$ON/*Brake Squeal/Mute/*Air$OFF/*Verbal Readout/*Air Blow Dn/*Air Water Injector/////////////////")
ROSTER(300,"PA# _300 Boxcab","LIghts/////////////////////////////")
ROSTER(722,"PA# _722 2-8-0","LIghts/////////////////////////////")
ROSTER(1010,"PA# __10 3t Shay","Lights/////////////////////////////")
ROSTER(1011,"PA# __11 cA Climax","Lights/////////////////////////////")
ROSTER(1013,"PA# __13 Goose","/////////////////////////////")
ROSTER(1014,"PA# __14 2-8-0","LIghts/////////////////////////////")
ROSTER(1022,"PA# __22 4-4-0","LIghts/////////////////////////////")
ROSTER(1060,"PA# __60 4-4-0","Lights/////////////////////////////")
ROSTER(1001,"PA# ___1 3t Shay","Lights/////////////////////////////")
ROSTER(1002,"PA# ___2 2t Shay","Lights/////////////////////////////")
ROSTER(1003,"PA# ___3 2t Shay","Lights/////////////////////////////")
ROSTER(1004,"PA# ___4 2t Shay","Lights/////////////////////////////")
ROSTER(1005,"PA# ___5 3t Shay","Lights/////////////////////////////")
ROSTER(1006,"PA# ___6 3t Shay","Lights/////////////////////////////")
ROSTER(1008,"PA# ___8 3t Shay","Lights/////////////////////////////")
ROSTER(1009,"PA# ___9 cB Climax","/////////////////////////////")
//duplicate address not supported, skipping: ROSTER(1001,"PA- 1001 36ft Stock Car","/////////////////////////////")
ROSTER(1432,"PA- 1432","LIghts/////////////////////////////")
ROSTER(2149,"PA- 2149","LIghts/////////////////////////////")
ROSTER(2188,"PA- 2188","Light/////////////////////////////")
ROSTER(2307,"PA- 2307","Light/////////////////////////////")
ROSTER(4016,"PA- 4016 2-8-2","/////////////////////////////")
ROSTER(5103,"PA- 5103","/////////////////////////////")
ROSTER(6421,"PA- 6421 Cleaner","/////////////////////////////")
ROSTER(141,"PA- _141","Lights/////////////////////////////")
ROSTER(306,"PA- _306 F7A Santa Fe","/////////////////////////////")
ROSTER(307,"PA- _307 F3B Santa Fe","/////////////////////////////")
ROSTER(376,"PA- _376 2-8-8-2","Light/////////////////////////////")
ROSTER(412,"PA- _412","LIghts/////////////////////////////")
ROSTER(432,"PA- _432 Baggage Car Snd","Light/Bell/*Horn/Air Release/Coupling/Brake Release-Squeal/Dynamic Brake/Air Hose-Uncoupling Lever/Shut Down-Notch Down/Fan-Notch Up/Rail Clack/Traction Air Compressor/Volume On-Off/Reduce Volume/Increase Volume/Air Compressor/Flange Squeal/Air Release/Bell Type/Horn Type/Loco Sound/Bell Volume/Horn Volume/Diesel Rumble Volume/Safety Valve/Air Release/Flange Noise 3/Sand Drop/Air Compressor Speed/")
//duplicate address not supported, skipping: ROSTER(432,"PA- _432 FP-7 A Unit","/////////////////////////////")
ROSTER(479,"PA- _479","LIghts/////////////////////////////")
//duplicate address not supported, skipping: ROSTER(722,"PA- _722","Lights/////////////////////////////")
//duplicate address not supported, skipping: ROSTER(722,"PA- _722 BX snd","Lights/Bell/*Whistle/*Long Air Release/*Coupling 1/*Brake Squeal-Release/Chuff On-Off/*Firebox Open-Close/*Water Injector/*Metel Crank Sound on-oof/*Water Filling/*Blower hiss/Mute On-Off/*Vol -/*Vol +/*Flange noise/*Shoveling/*Coal auger/*Bell Type (7)/*Whis. Type (17)/*Air hose firing/*Flange Noise/*Ass.Loco Sound/*Flange noise/*Chuff Type/*Long air Release/*Sand Droping/*Assoc Loco Sound//")
ROSTER(15,"PA- __15","Light/////////////////////////////")
ROSTER(16,"PA- __16","/////////////////////////////")
ROSTER(60,"PA- __60","Light/////////////////////////////")
ROSTER(61,"PA- __61","Lights/////////////////////////////")
ROSTER(77,"PA- __77 PA Stanta Fe","/////////////////////////////")
ROSTER(5,"PA- ___5 Galloping Goose","/////////////////////////////")
ROSTER(9,"PA- ___9","/////////////////////////////")
ROSTER(3780,"PRA- 3780 4-8-4 Santa Fe","/////////////////////////////")
ROSTER(3,"x ESU docoder with dead sound","Light//*Horn///////////////////////////")
//duplicate address not supported, skipping: ROSTER(61,"x long addr test","/////////////////////////////")
ROSTER(721,"X PA# _722 2-6-2","/////////////////////////////")
ROSTER(14,"X RH 14","/////////////////////////////")
ROSTER(3830,"Z old chip N12SR NCE","/////////////////////////////")
//copy the lines above into your myAutomation.h file for EX-CommandStation


ROSTER(111,"Loco 111","F0/F1/*F2/F3/F4/F5/F6/F7/F8")
ROSTER(222,"Loco 222","F0/F1/*F2/F3/F4/F5/F6/F7/F8/F9")
ROSTER(333,"Loco 333","F0/F1/*F2/F3/F4/F5/F6/F7/F8/F9/F10")
ROSTER(444,"Loco 444 32fns","F0/F1/*F2/F3/F4/F5/F6/F7/F8/F9/10/F11/F12/F13/F14/F15/F16/F17/F18/F19/F20/F21/F22/F23/F24/F25/F26/27/F28/F29/F30/F31")
ROSTER(555,"Loco 555","F0/F1/*F2/F3/F4/F5/F6/F7/F8/F9/10/F11/F12/F13/F14/F15//F17/F18//F20//F22//F24//F26/27///F30/F31")
ROSTER(666,"Loco 666","F0/F1/*F2///  /F6/  /  /  /10/F11")
ROSTER(10,"DC BLOCK A","")
ROSTER(20,"DC BLOCK B","////////////////////////////")
