// All aliases live here.

// Turnout ID aliases
// **These are turnout IDs and do not always map to point IDs to spread load
// across CDUs**
ALIAS(POINT_LOOP_STATION_ENTRY, 1)
ALIAS(POINT_LOOP_STATION_EXIT, 2)
ALIAS(POINT_LOOP_SIDING, 3)
ALIAS(POINT_LOOP_YARD, 4)
ALIAS(POINT_MAIN_TURNTABLE, 5)
ALIAS(POINT_MAIN_YARD, 6)
ALIAS(POINT_YARD_SIDING_1, 7)
ALIAS(POINT_YARD_LOOP, 8)

// Point Vpin aliases - MCP23017 at 0x20
// **Point numbers are physical number refs, not turnout IDs**
ALIAS(POINT_1_EN, 200)  // GPA0
ALIAS(POINT_1_DIR, 201) // GPA1
ALIAS(POINT_2_EN, 202)  // GPA2
ALIAS(POINT_2_DIR, 203) // GPA3
ALIAS(POINT_3_EN, 204)  // GPA4
ALIAS(POINT_3_DIR, 205) // GPA5
ALIAS(POINT_4_EN, 206)  // GPA6
ALIAS(POINT_4_DIR, 207) // GPA7
ALIAS(POINT_5_EN, 208)  // GPB0
ALIAS(POINT_5_DIR, 209) // GPB1
ALIAS(POINT_6_EN, 210)  // GPB2
ALIAS(POINT_6_DIR, 211) // GPB3
ALIAS(POINT_7_EN, 212)  // GPB4
ALIAS(POINT_7_DIR, 213) // GPB5
ALIAS(POINT_8_EN, 214)  // GPB6
ALIAS(POINT_8_DIR, 215) // GPB7

// Mimic panel Vpin aliases
// **Avoid GPA7|B7 as inputs**
// MCP23017 at 0x21
ALIAS(POINT_LOOP_YARD_BUTTON, 300)          // GPA0
ALIAS(POINT_LOOP_YARD_LED, 301)             // GPA1
ALIAS(DECOUPLER_LOOP_SIDING_BUTTON, 302)    // GPA2
ALIAS(DECOUPLER_LOOP_SIDING_LED, 303)       // GPA3
ALIAS(POINT_LOOP_STATION_ENTRY_BUTTON, 304) // GPA4
ALIAS(POINT_LOOP_STATION_ENTRY_LED, 305)    // GPA5
ALIAS(POINT_LOOP_SIDING_BUTTON, 306)        // GPA6
ALIAS(POINT_LOOP_SIDING_LED, 307)           // GPA7
ALIAS(POINT_LOOP_STATION_EXIT_BUTTON, 308)  // GPB0
ALIAS(POINT_LOOP_STATION_EXIT_LED, 309)     // GPB1
ALIAS(DECOUPLER_SIDING_2_BUTTON, 310)       // GPB2
ALIAS(DECOUPLER_SIDING_2_LED, 311)          // GPB3
ALIAS(POINT_YARD_LOOP_BUTTON, 312)          // GPB4
ALIAS(POINT_YARD_LOOP_LED, 313)             // GPB5
ALIAS(DECOUPLER_SIDING_1_BUTTON, 314)       // GPB6
ALIAS(DECOUPLER_SIDING_1_LED, 315)          // GPB7
// MCP23017 at 0x22
ALIAS(DECOUPLER_MAIN_BUTTON, 320)       // GPA0
ALIAS(DECOUPLER_MAIN_LED, 321)          // GPA1
ALIAS(POINT_YARD_SIDING_1_BUTTON, 322)  // GPA2
ALIAS(POINT_YARD_SIDING_1_LED, 323)     // GPA3
ALIAS(POINT_MAIN_YARD_BUTTON, 324)      // GPA4
ALIAS(POINT_MAIN_YARD_LED, 325)         // GPA5
ALIAS(POINT_MAIN_TURNTABLE_BUTTON, 326) // GPA6
ALIAS(POINT_MAIN_TURNTABLE_LED, 327)    // GPA7
ALIAS(SHUNT_REVERSE_BUTTON, 328)        // GPB0
ALIAS(TRACK_B_OVERLOAD_LED, 329)        // GPB1
ALIAS(SHUNT_FORWARD_BUTTON, 330)        // GPB2
ALIAS(TRACK_A_OVERLOAD_LED, 331)        // GPB3
ALIAS(MUTE_OVERLOAD_BUZZER_BUTTON, 332) // GPB4
ALIAS(TRACK_POWER_LED, 333)             // GPB5
ALIAS(TRACK_POWER_BUTTON, 334)          // GPB6
ALIAS(TRACK_OVERLOAD_BUZZER, 335)       // GPB7

// Decoupler route and Vpin aliases
ALIAS(DECOUPLER_MAIN, 100)
ALIAS(DECOUPLER_MAIN_SERVO, 100)
ALIAS(DECOUPLER_SIDING_1, 101)
ALIAS(DECOUPLER_SIDING_1_SERVO, 101)
ALIAS(DECOUPLER_SIDING_2, 102)
ALIAS(DECOUPLER_SIDING_2_SERVO, 102)
ALIAS(DECOUPLER_LOOP_SIDING, 103)
ALIAS(DECOUPLER_LOOP_SIDING_SERVO, 103)

// General route aliases
ALIAS(DISPLAY_STARTUP, 400)
ALIAS(CLOSE_ALL_POINTS, 401)
ALIAS(TURNTABLE_STARTUP, 402)

// Signal aliases
/* Placeholders
ALIAS(SIGNAL_1,104)
ALIAS(SIGNAL_2,105)
ALIAS(SIGNAL_3,106)
ALIAS(SIGNAL_4,107)
ALIAS(SIGNAL_5,108)
ALIAS(SIGNAL_6,109)
ALIAS(SIGNAL_7,110)
ALIAS(SIGNAL_8,111)
ALIAS(SIGNAL_9,112)
ALIAS(SIGNAL_10,113)
ALIAS(SIGNAL_11,114)
ALIAS(SIGNAL_12,115)
*/

// Turntable aliases.
ALIAS(TURNTABLE_ID, 1)
ALIAS(TURNTABLE_VPIN, 600)
ALIAS(TURNTABLE_STORAGE_1, 1)
ALIAS(TURNTABLE_STORAGE_2, 2)
ALIAS(TURNTABLE_STORAGE_3, 3)
ALIAS(TURNTABLE_STORAGE_4, 4)
ALIAS(TURNTABLE_STORAGE_5, 5)
ALIAS(TURNTABLE_MAIN, 6)

// SensorCAM aliases
ALIAS(SENSORCAM_LEFT, 700)
ALIAS(SENSORCAM_RIGHT, 800)
