// All aliases live here.

// Point/turnout aliases
ALIAS(POINT_LOOP_STATION_ENTRY)
ALIAS(POINT_LOOP_STATION_EXIT)
ALIAS(POINT_MAIN_TURNTABLE)
ALIAS(POINT_MAIN_YARD)
ALIAS(POINT_YARD_SIDING_1)
ALIAS(POINT_YARD_SIDING_2_LOOP)
ALIAS(POINT_LOOP_YARD_SIDING_2)

// Decoupler aliases
ALIAS(DECOUPLER_MAIN, 100)
ALIAS(DECOUPLER_SIDING_1, 101)
ALIAS(DECOUPLER_SIDING_2, 102)

// Turntable aliases.
ALIAS(TURNTABLE_ID, 1)
ALIAS(TURNTABLE_VPIN, 600)
ALIAS(TURNTABLE_STORAGE_1, 1)
ALIAS(TURNTABLE_STORAGE_2, 2)
ALIAS(TURNTABLE_STORAGE_3, 3)
ALIAS(TURNTABLE_STORAGE_4, 4)
ALIAS(TURNTABLE_STORAGE_5, 5)
ALIAS(TURNTABLE_MAIN, 6)
