// Mimic panel event handlers go here

// Overload A controls the LED and buzzer
ONOVERLOAD(A)
  SET(TRACK_A_OVERLOAD_LED)
  SET(TRACK_OVERLOAD_BUZZER)
  SCREEN(1,0,"Track A OVERLOAD!")
  AFTEROVERLOAD(A)
  RESET(TRACK_A_OVERLOAD_LED)
  RESET(TRACK_OVERLOAD_BUZZER)
  SCREEN(1,0,"Cleared A overload")
  DELAY(3000)
  SCREEN(1,0,"")
DONE

// Overload B controls the LED and buzzer
ONOVERLOAD(B)
  SET(TRACK_B_OVERLOAD_LED)
  SET(TRACK_OVERLOAD_BUZZER)
  SCREEN(1,1,"Track B OVERLOAD!")
  AFTEROVERLOAD(B)
  RESET(TRACK_B_OVERLOAD_LED)
  RESET(TRACK_OVERLOAD_BUZZER)
  SCREEN(1,1,"Cleared B overload")
  DELAY(3000)
  SCREEN(1,1,"")
DONE

// Track power button is emergency power off
ONBUTTON(TRACK_POWER_BUTTON)
  POWEROFF
DONE

// Reset overload buzzer button turns the buzzer off
ONBUTTON(MUTE_OVERLOAD_BUZZER_BUTTON)
  RESET(TRACK_OVERLOAD_BUZZER)
DONE

// Point control buttons
ONBUTTON(POINT_LOOP_STATION_ENTRY_BUTTON)
  TOGGLE_TURNOUT(POINT_LOOP_STATION_ENTRY)
DONE


ONBUTTON(POINT_LOOP_STATION_EXIT_BUTTON)
  TOGGLE_TURNOUT(POINT_LOOP_STATION_EXIT)
DONE

ONBUTTON(POINT_LOOP_SIDING_BUTTON)
  TOGGLE_TURNOUT(POINT_LOOP_SIDING)
DONE

ONBUTTON(POINT_LOOP_YARD_BUTTON)
  TOGGLE_TURNOUT(POINT_LOOP_YARD)
DONE

ONBUTTON(POINT_MAIN_TURNTABLE_BUTTON)
  TOGGLE_TURNOUT(POINT_MAIN_TURNTABLE)
DONE

ONBUTTON(POINT_MAIN_YARD_BUTTON)
  TOGGLE_TURNOUT(POINT_MAIN_YARD)
DONE

ONBUTTON(POINT_YARD_SIDING_1_BUTTON)
  TOGGLE_TURNOUT(POINT_YARD_SIDING_1)
DONE

ONBUTTON(POINT_YARD_LOOP_BUTTON)
  TOGGLE_TURNOUT(POINT_YARD_LOOP)
DONE
