// Route definitions here

// Startup sequence to show all is ready
AUTOSTART
SEQUENCE(DISPLAY_STARTUP)
SCREEN(1,0,"Shelf layout ready")
DONE

// Startup route to close all points
AUTOSTART
ROUTE(CLOSE_ALL_POINTS,"Close all points")
  CLOSE(POINT_LOOP_STATION_ENTRY)
  CLOSE(POINT_LOOP_SIDING)
  CLOSE(POINT_MAIN_TURNTABLE)
  CLOSE(POINT_YARD_SIDING_1)
  DELAY(4000) // Let CDUs recharge
  CLOSE(POINT_LOOP_STATION_EXIT)
  CLOSE(POINT_LOOP_YARD)
  CLOSE(POINT_MAIN_YARD)
  CLOSE(POINT_YARD_LOOP)
DONE

// Startup route to set turntable to storage 1
AUTOSTART
ROUTE(TURNTABLE_STARTUP,"Start turntable at Storage 1")
  ROTATE(TURNTABLE_ID,TURNTABLE_STORAGE_1,Turn)
DONE
