// Turntable definitions
EXTT_TURNTABLE(TURNTABLE_ID,TURNTABLE_VPIN,270,"Turntable")
TT_ADDPOSITION(TURNTABLE_ID,TURNTABLE_STORAGE_1,200,190,"Storage Track 1")
TT_ADDPOSITION(TURNTABLE_ID,TURNTABLE_STORAGE_2,300,200,"Storage Track 2")
TT_ADDPOSITION(TURNTABLE_ID,TURNTABLE_STORAGE_3,400,210,"Storage Track 3")
TT_ADDPOSITION(TURNTABLE_ID,TURNTABLE_STORAGE_4,500,220,"Storage Track 4")
TT_ADDPOSITION(TURNTABLE_ID,TURNTABLE_STORAGE_5,600,230,"Storage Track 5")
TT_ADDPOSITION(TURNTABLE_ID,TURNTABLE_MAIN,1000,300,"Main Connection")
