// Sequences for my mimic panel
// Point LEDs are set/unset via macro in myPoints.h
// Decoupler LEDs are set/unset via macro in myDecouplers.h

AUTOSTART SEQUENCE(100)
  IF(POINT1_CLOSE)
    CLOSE(STATION_SIDING_WEST)
  ENDIF
  IF(POINT1_THROW)
    THROW(STATION_SIDING_WEST)
  ENDIF
  IF(POINT2_CLOSE)
    CLOSE(STATION_SIDING_WEST)
  ENDIF
  IF(POINT2_THROW)
    THROW(STATION_SIDING_WEST)
  ENDIF
  IF(POINT3_CLOSE)
    CLOSE(STATION_SIDING_EAST)
  ENDIF
  IF(POINT3_THROW)
    THROW(STATION_SIDING_EAST)
  ENDIF
  IF(POINT4_CLOSE)
    CLOSE(STATION_SIDING_EAST)
  ENDIF
  IF(POINT4_THROW)
    THROW(STATION_SIDING_EAST)
  ENDIF
  IF(POINT5_CLOSE)
    CLOSE(CONTAINER_SIDING)
  ENDIF
  IF(POINT5_THROW)
    THROW(CONTAINER_SIDING)
  ENDIF
  IF(POINT6_CLOSE)
    CLOSE(CAR_SIDING)
  ENDIF
  IF(POINT6_THROW)
    THROW(CAR_SIDING)
  ENDIF
  IF(POINT7_CLOSE)
    CLOSE(WAREHOUSE_SIDING)
  ENDIF
  IF(POINT7_THROW)
    THROW(WAREHOUSE_SIDING)
  ENDIF
  IF(POINT8_CLOSE)
    CLOSE(INDUSTRY_LOOP_EAST)
  ENDIF
  IF(POINT8_THROW)
    THROW(INDUSTRY_LOOP_EAST)
  ENDIF
  IF(POINT9_CLOSE)
    CLOSE(TURNTABLE_ACCESS)
  ENDIF
  IF(POINT9_THROW)
    THROW(TURNTABLE_ACCESS)
  ENDIF
  IF(POINT10_CLOSE)
    CLOSE(STORAGE_3)
  ENDIF
  IF(POINT10_THROW)
    THROW(STORAGE_3)
  ENDIF
  IF(POINT11_CLOSE)
    CLOSE(STORAGE_2)
  ENDIF
  IF(POINT11_THROW)
    THROW(STORAGE_2)
  ENDIF
  IF(POINT12_CLOSE)
    CLOSE(MAINTENANCE)
  ENDIF
  IF(POINT12_THROW)
    THROW(MAINTENANCE)
  ENDIF
  IF(POINT13_CLOSE)
    CLOSE(STORAGE_1_MAINTENANCE)
  ENDIF
  IF(POINT13_THROW)
    THROW(STORAGE_1_MAINTENANCE)
  ENDIF
  IF(POINT14_CLOSE)
    CLOSE(YARD_ACCESS)
  ENDIF
  IF(POINT14_THROW)
    THROW(YARD_ACCESS)
  ENDIF
  IF(POINT15_CLOSE)
    CLOSE(INDUSTRY_LOOP_WEST)
  ENDIF
  IF(POINT15_THROW)
    THROW(INDUSTRY_LOOP_WEST)
  ENDIF
  IF(DECOUPLER1_BUTTON)
    START(WAREHOUSE_DECOUPLER)
  ENDIF
  IF(DECOUPLER2_BUTTON)
    START(CAR_DECOUPLER)
  ENDIF
  IF(DECOUPLER3_BUTTON)
    START(CONTAINER_DECOUPLER)
  ENDIF
  IF(DECOUPLER4_BUTTON)
    START(STORAGE3_DECOUPLER)
  ENDIF
  IF(DECOUPLER5_BUTTON)
    START(STORAGE2_DECOUPLER)
  ENDIF
  IF(DECOUPLER6_BUTTON)
    START(STORAGE1_DECOUPLER)
  ENDIF
  IF(DECOUPLER7_BUTTON)
    START(MAINTENANCE_DECOUPLER)
  ENDIF
FOLLOW(100)

// Event handler for the rotary encoder/turntable controller
// Blackpill at 0x70, Vpin 700

ONCHANGE(700)
  IFRE(700, 1)
    START(TTROUTE1)
  ENDIF
  IFRE(700, 2)
    START(TTROUTE2)
  ENDIF
  IFRE(700, 3)
    START(TTROUTE3)
  ENDIF
  IFRE(700, 4)
    START(TTROUTE4)
  ENDIF
  IFRE(700, 5)
    START(TTROUTE5)
  ENDIF
  IFRE(700, 6)
    START(TTROUTE6)
  ENDIF
  IFRE(700, 7)
    START(TTROUTE7)
  ENDIF
  IFRE(700, 8)
    START(TTROUTE8)
  ENDIF
  IFRE(700, 9)
    START(TTROUTE9)
  ENDIF
  IFRE(700, 10)
    START(TTROUTE10)
  ENDIF
DONE
