// Sequences for my mimic panel
// Point LEDs are set/reset via macro in myPoints.h
// Decoupler LEDs are set/reset via macro in myDecouplers.h

AUTOSTART SEQUENCE(100)
  IF(DECOUPLER1_BUTTON)
    START(WAREHOUSE_DECOUPLER)
  ENDIF
  IF(DECOUPLER2_BUTTON)
    START(CAR_DECOUPLER)
  ENDIF
  IF(DECOUPLER3_BUTTON)
    START(CONTAINER_DECOUPLER)
  ENDIF
  IF(DECOUPLER4_BUTTON)
    START(STORAGE3_DECOUPLER)
  ENDIF
  IF(DECOUPLER5_BUTTON)
    START(STORAGE2_DECOUPLER)
  ENDIF
  IF(DECOUPLER6_BUTTON)
    START(STORAGE1_DECOUPLER)
  ENDIF
  IF(DECOUPLER7_BUTTON)
    START(MAINTENANCE_DECOUPLER)
  ENDIF
FOLLOW(100)

// Event handler for the rotary encoder/turntable controller
// Blackpill at 0x70, Vpin 700

ONCHANGE(700)
  IFRE(700, 0)
    START(TTROUTE_9)
  ENDIF
  IFRE(700, 1)
    START(TTROUTE_1)
  ENDIF
  IFRE(700, 2)
    START(TTROUTE_2)
  ENDIF
  IFRE(700, 3)
    START(TTROUTE_3)
  ENDIF
  IFRE(700, 4)
    START(TTROUTE_4)
  ENDIF
  IFRE(700, 5)
    START(TTROUTE_5)
  ENDIF
  IFRE(700, 6)
    START(TTROUTE_6)
  ENDIF
  IFRE(700, 7)
    START(TTROUTE_7)
  ENDIF
  IFRE(700, 8)
    START(TTROUTE_8)
  ENDIF
DONE
